EVENTS_EMIT = {
    "JOINED_ROOM": "GAME:ROOMS:JOIN:SUCCESS",
    "CREATED_ROOM": "GAME:ROOMS:CREATE:SUCCESS",
}

EVENTS_ON = {
    "GET_ROOMS": "GAME:ROOMS:GET",
    "JOIN_ROOM": "GAME:ROOMS:JOIN",
    "CREATE_ROOM": "GAME:ROOMS:CREATE",
}
