EVENTS_EMIT = {
    "NEXT_TURN": "GAME:TURN:NEXT",
    "GAME_STARTED": "GAME:START:SUCCESS",
    "LEFT_ROOM": "GAME:ROOMS:LEAVE:SUCCESS",
    "GAME_CANCELLED": "GAME:CANCEL:SUCCESS",
    "JOINED_ROOM": "GAME:ROOMS:JOIN:SUCCESS",
    "CREATED_ROOM": "GAME:ROOMS:CREATE:SUCCESS",
    "DICE_PROCESSED": "GAME:DICE:PROCESS:SUCCESS",
    "EXCHANGED_TOKENS": "GAME:TOKEN:EXCHANGE:SUCCESS",
}

EVENTS_ON = {
    "START_GAME": "GAME:START",
    "CANCEL_GAME": "GAME:CANCEL",
    "GET_ROOMS": "GAME:ROOMS:GET",
    "JOIN_ROOM": "GAME:ROOMS:JOIN",
    "LEAVE_ROOM": "GAME:ROOMS:LEAVE",
    "CREATE_ROOM": "GAME:ROOMS:CREATE",
    "PROCESS_DICE": "GAME:DICE:PROCESS",
    "COMPLETE_TURN": "GAME:TURN:COMPLETE",
    "EXCHANGE_TOKENS": "GAME:TOKENS:EXCHANGE",
    "GET_CURRENT_ROOM": "GAME:ROOMS:CURRENT:GET",
}
