# Generated by Django 3.1.5 on 2021-03-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rabbits', models.IntegerField(default=0)),
                ('sheep', models.IntegerField(default=0)),
                ('pigs', models.IntegerField(default=0)),
                ('cows', models.IntegerField(default=0)),
                ('horses', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_states', to='game.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authorization.user')),
            ],
        ),
    ]
