# Generated by Django 3.1.7 on 2021-04-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='has_big_dog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='has_small_dog',
            field=models.BooleanField(default=False),
        ),
    ]
