# Generated by Django 3.1.7 on 2021-05-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_room_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_turn',
            field=models.IntegerField(default=1),
        ),
    ]
