# Generated by Django 3.1.7 on 2021-05-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_current_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_processed_dice',
            field=models.IntegerField(default=0),
        ),
    ]
