# Generated by Django 3.1.7 on 2021-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20210404_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_in_room',
            field=models.IntegerField(default=0),
        ),
    ]
